#!/bin/sh /etc/rc.common
# Swap to the SD card if one turns up within two minutes of the end of boot
# (see /usr/bin/yun-sdswap). START=99: this is the last thing boot starts.

START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/yun-sdswap wait
	procd_close_instance
}
